In [1]:
#  求解线性方程组

from scipy import linalg
import numpy as np

# x1 + x2 + 7*x3 = 2
# 2*x1 + 3*x2 + 5*x3 = 3
# 4*x1 + 2*x2 + 6*x3 = 4

A = np.array([[1, 1, 7], [2, 3, 5], [4, 2, 6]])  # A代表系数矩阵
b = np.array([2, 3, 4])  # b代表常数列
x = linalg.solve(A, b)
print(x)


[0.6  0.35 0.15]


In [11]:
#阶乘
s=0
def jiecheng(i):
    a=1
    for k in range(1,i+1):
        #print(k)
        a=a*k
    return a
for i in range(1,11):
    j=jiecheng(i)
    #print(j)
    s = s+j
print(s)
    

4037913


In [20]:
import pandas as pd

a = 5*np.eye(5,dtype=int)+(-1)*np.eye(5,k=-1,dtype=int)

print(a)
pd.DataFrame(a)


[[ 5  0  0  0  0]
 [-1  5  0  0  0]
 [ 0 -1  5  0  0]
 [ 0  0 -1  5  0]
 [ 0  0  0 -1  5]]


0  1  2  3  4
0  5  0  0  0  0
1 -1  5  0  0  0
2  0 -1  5  0  0
3  0  0 -1  5  0
4  0  0  0 -1  5

In [2]:
#判断输入数n是否为Fibonacci数。
#输入正整数N，输出比N小的最大素数Fibonacci数和比N大的最小素数Fibonacci数

num = int(input("请输入一个整数："))
a = 0
b = 1
i = 0
t = 0
while a<num:
    t = a
    a,b = b,a+b
    i += 1
if a == num:
    print("{}是第{}位斐波那契数".format(num,i))
else:
    print("{}不是一个斐波那契数".format(num),end=',')
if num-t>a-num:
    print("{}是距{}最近的斐波那契数".format(a,num))
elif num-t<a-num:
    print("{}是距{}最近的斐波那契数".format(t, num))
elif num-t == a - num:
    print("{},{}是距离{}最近的斐波那契数".format(t,a,num))


请输入一个整数：7
7不是一个斐波那契数,8是距7最近的斐波那契数


In [ ]:
num = int(input("请输入一个整数："))
# 质数大于 1
if num > 1:
   # 查看因子
   for i in range(2,num):
        if (num % i) == 0:
            print(num,"不是质数")
            print(i,"乘于",num//i,"是",num)
            break
        else:
            print(num,"是质数")

# 如果输入的数字小于或等于 1，不是质数
else:
    print(num,"不是质数")
    


In [5]:
def jisuanxingqi (a):
    b = a%7 
    if b in [0,1,2,3,4,5]:
        i=2+b-1
        print("这天是星期{}".format(i))
    elif b==6 :
        print("这天是星期日")

def tianshu(a,b):
    y = [31,28,31,30,31,30,31,31,30,31,30,31]
    k=b
    for i in range(1,a+1):
        k = k+y[i]
    return k


num1 = int(input("请输入月份："))
num2 = int(input("请输入日期："))

k=tianshu(num1,num2)
jisuanxingqi(k)
    

请输入月份：3
请输入日期：5
这天是星期4


In [7]:
num3 = list(input("请输入一个八位整数"))
num1 = int(str(num3[4])+str(num3[5]))
num1 = int(str(num3[6])+str(num3[7]))
k=tianshu(num1,num2)
print(k)

请输入一个八位整数20190805
155
